- oaesis is now built with libotosis instead of mintwrappers. For some reason   the startup is incredibly slow right now. - The version is now exactly the same as the suffix of liboaesis

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -28,11 +28,11 @@ ac_help="$ac_help
 ac_help="$ac_help
   --disable-ovdisistest       Do not try to compile and run a test oVDIsis program"
 ac_help="$ac_help
-  --with-mintwrappers-prefix=PFX   Prefix where mintwrappers is installed (optional)"
+  --with-otosis-prefix=PFX   Prefix where otosis is installed (optional)"
 ac_help="$ac_help
-  --with-mintwrappers-exec-prefix=PFX Exec prefix where mintwrappers is installed (optional)"
+  --with-otosis-exec-prefix=PFX Exec prefix where otosis is installed (optional)"
 ac_help="$ac_help
-  --disable-mintwrapperstest       Do not try to compile and run a test mintwrappers program"
+  --disable-otosistest       Do not try to compile and run a test otosis program"
 
 # Initialize some variables set by options.
 # The variables have the same names as the options, with
@@ -544,9 +544,9 @@ fi
 . $srcdir/OAESIS-VERSION
 
 LT_RELEASE=$OAESIS_MAJOR_VERSION.$OAESIS_MINOR_VERSION
-LT_CURRENT=`expr $OAESIS_MICRO_VERSION - $OAESIS_INTERFACE_AGE`
-LT_REVISION=$OAESIS_INTERFACE_AGE
-LT_AGE=`expr $OAESIS_BINARY_AGE - $OAESIS_INTERFACE_AGE`
+LT_CURRENT=`expr $OAESIS_MAJOR_VERSION + $OAESIS_MINOR_VERSION`
+LT_REVISION=$OAESIS_MICRO_VERSION
+LT_AGE=$OAESIS_MINOR_VERSION
 LT_VERSION_INFO="-version-info $LT_CURRENT:$LT_REVISION:$LT_AGE"
 
 ac_aux_dir=
@@ -1786,164 +1786,164 @@ else
   
 fi
 
-if test x$with_mintwrappers = xyes ; then
+if test x$with_otosis = xyes ; then
   { echo "configure: error: 
-*** Directory must be specified for --with-mintwrappers" 1>&2; exit 1; }
+*** Directory must be specified for --with-otosis" 1>&2; exit 1; }
 fi
 
-if test x$with_mintwrappers = x ; then 
-  # Look for separately installed mintwrappers
+if test x$with_otosis = x ; then 
+  # Look for separately installed otosis
 
-  # Check whether --with-mintwrappers-prefix or --without-mintwrappers-prefix was given.
-if test "${with_mintwrappers_prefix+set}" = set; then
-  withval="$with_mintwrappers_prefix"
-  mintwrappers_config_prefix="$withval"
+  # Check whether --with-otosis-prefix or --without-otosis-prefix was given.
+if test "${with_otosis_prefix+set}" = set; then
+  withval="$with_otosis_prefix"
+  otosis_config_prefix="$withval"
 else
-  mintwrappers_config_prefix=""
+  otosis_config_prefix=""
 fi
 
-# Check whether --with-mintwrappers-exec-prefix or --without-mintwrappers-exec-prefix was given.
-if test "${with_mintwrappers_exec_prefix+set}" = set; then
-  withval="$with_mintwrappers_exec_prefix"
-  mintwrappers_config_exec_prefix="$withval"
+# Check whether --with-otosis-exec-prefix or --without-otosis-exec-prefix was given.
+if test "${with_otosis_exec_prefix+set}" = set; then
+  withval="$with_otosis_exec_prefix"
+  otosis_config_exec_prefix="$withval"
 else
-  mintwrappers_config_exec_prefix=""
+  otosis_config_exec_prefix=""
 fi
 
-# Check whether --enable-mintwrapperstest or --disable-mintwrapperstest was given.
-if test "${enable_mintwrapperstest+set}" = set; then
-  enableval="$enable_mintwrapperstest"
+# Check whether --enable-otosistest or --disable-otosistest was given.
+if test "${enable_otosistest+set}" = set; then
+  enableval="$enable_otosistest"
   :
 else
-  enable_mintwrapperstest=yes
+  enable_otosistest=yes
 fi
 
 
-  if test x$mintwrappers_config_exec_prefix != x ; then
-     mintwrappers_config_args="$mintwrappers_config_args --exec-prefix=$mintwrappers_config_exec_prefix"
-     if test x${MINTWRAPPERS_CONFIG+set} != xset ; then
-        MINTWRAPPERS_CONFIG=$mintwrappers_config_exec_prefix/bin/mintwrappers-config
+  if test x$otosis_config_exec_prefix != x ; then
+     otosis_config_args="$otosis_config_args --exec-prefix=$otosis_config_exec_prefix"
+     if test x${OTOSIS_CONFIG+set} != xset ; then
+        OTOSIS_CONFIG=$otosis_config_exec_prefix/bin/otosis-config
      fi
   fi
-  if test x$mintwrappers_config_prefix != x ; then
-     mintwrappers_config_args="$mintwrappers_config_args --prefix=$mintwrappers_config_prefix"
-     if test x${MINTWRAPPERS_CONFIG+set} != xset ; then
-        MINTWRAPPERS_CONFIG=$mintwrappers_config_prefix/bin/mintwrappers-config
+  if test x$otosis_config_prefix != x ; then
+     otosis_config_args="$otosis_config_args --prefix=$otosis_config_prefix"
+     if test x${OTOSIS_CONFIG+set} != xset ; then
+        OTOSIS_CONFIG=$otosis_config_prefix/bin/otosis-config
      fi
   fi
 
-  # Extract the first word of "mintwrappers-config", so it can be a program name with args.
-set dummy mintwrappers-config; ac_word=$2
+  # Extract the first word of "otosis-config", so it can be a program name with args.
+set dummy otosis-config; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
 echo "configure:1839: checking for $ac_word" >&5
-if eval "test \"`echo '$''{'ac_cv_path_MINTWRAPPERS_CONFIG'+set}'`\" = set"; then
+if eval "test \"`echo '$''{'ac_cv_path_OTOSIS_CONFIG'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
-  case "$MINTWRAPPERS_CONFIG" in
+  case "$OTOSIS_CONFIG" in
   /*)
-  ac_cv_path_MINTWRAPPERS_CONFIG="$MINTWRAPPERS_CONFIG" # Let the user override the test with a path.
+  ac_cv_path_OTOSIS_CONFIG="$OTOSIS_CONFIG" # Let the user override the test with a path.
   ;;
   *)
   IFS="${IFS= 	}"; ac_save_ifs="$IFS"; IFS="${IFS}:"
   for ac_dir in $PATH; do
     test -z "$ac_dir" && ac_dir=.
     if test -f $ac_dir/$ac_word; then
-      ac_cv_path_MINTWRAPPERS_CONFIG="$ac_dir/$ac_word"
+      ac_cv_path_OTOSIS_CONFIG="$ac_dir/$ac_word"
       break
     fi
   done
   IFS="$ac_save_ifs"
-  test -z "$ac_cv_path_MINTWRAPPERS_CONFIG" && ac_cv_path_MINTWRAPPERS_CONFIG="no"
+  test -z "$ac_cv_path_OTOSIS_CONFIG" && ac_cv_path_OTOSIS_CONFIG="no"
   ;;
 esac
 fi
-MINTWRAPPERS_CONFIG="$ac_cv_path_MINTWRAPPERS_CONFIG"
-if test -n "$MINTWRAPPERS_CONFIG"; then
-  echo "$ac_t""$MINTWRAPPERS_CONFIG" 1>&6
+OTOSIS_CONFIG="$ac_cv_path_OTOSIS_CONFIG"
+if test -n "$OTOSIS_CONFIG"; then
+  echo "$ac_t""$OTOSIS_CONFIG" 1>&6
 else
   echo "$ac_t""no" 1>&6
 fi
 
-  min_mintwrappers_version=0.0.0
-  echo $ac_n "checking for mintwrappers - version >= $min_mintwrappers_version""... $ac_c" 1>&6
-echo "configure:1870: checking for mintwrappers - version >= $min_mintwrappers_version" >&5
-  no_mintwrappers=""
-  if test "$MINTWRAPPERS_CONFIG" = "no" ; then
-    no_mintwrappers=yes
+  min_otosis_version=0.31.0
+  echo $ac_n "checking for otosis - version >= $min_otosis_version""... $ac_c" 1>&6
+echo "configure:1870: checking for otosis - version >= $min_otosis_version" >&5
+  no_otosis=""
+  if test "$OTOSIS_CONFIG" = "no" ; then
+    no_otosis=yes
   else
-    MINTWRAPPERS_CFLAGS=`$MINTWRAPPERS_CONFIG $mintwrappers_config_args --cflags`
-    MINTWRAPPERS_LIBS=`$MINTWRAPPERS_CONFIG $mintwrappers_config_args --libs`
-    mintwrappers_config_major_version=`$MINTWRAPPERS_CONFIG $mintwrappers_config_args --version | \
+    OTOSIS_CFLAGS=`$OTOSIS_CONFIG $otosis_config_args --cflags`
+    OTOSIS_LIBS=`$OTOSIS_CONFIG $otosis_config_args --libs`
+    otosis_config_major_version=`$OTOSIS_CONFIG $otosis_config_args --version | \
            sed 's/\([0-9]*\).\([0-9]*\).\([0-9]*\)/\1/'`
-    mintwrappers_config_minor_version=`$MINTWRAPPERS_CONFIG $mintwrappers_config_args --version | \
+    otosis_config_minor_version=`$OTOSIS_CONFIG $otosis_config_args --version | \
            sed 's/\([0-9]*\).\([0-9]*\).\([0-9]*\)/\2/'`
-    mintwrappers_config_micro_version=`$MINTWRAPPERS_CONFIG $mintwrappers_config_args --version | \
+    otosis_config_micro_version=`$OTOSIS_CONFIG $otosis_config_args --version | \
            sed 's/\([0-9]*\).\([0-9]*\).\([0-9]*\)/\3/'`
-    if test "x$enable_mintwrapperstest" = "xyes" ; then
+    if test "x$enable_otosistest" = "xyes" ; then
       ac_save_CFLAGS="$CFLAGS"
       ac_save_LIBS="$LIBS"
-      CFLAGS="$CFLAGS $MINTWRAPPERS_CFLAGS"
-      LIBS="$LIBS $MINTWRAPPERS_LIBS"
+      CFLAGS="$CFLAGS $OTOSIS_CFLAGS"
+      LIBS="$LIBS $OTOSIS_LIBS"
      fi
   fi
-  if test "x$no_mintwrappers" = x ; then
+  if test "x$no_otosis" = x ; then
      echo "$ac_t""yes" 1>&6
      :     
   else
      echo "$ac_t""no" 1>&6
-     if test "$MINTWRAPPERS_CONFIG" = "no" ; then
-       echo "*** The mintwrappers-config script installed by mintwrappers could not be found"
-       echo "*** If mintwrappers was installed in PREFIX, make sure PREFIX/bin is in"
-       echo "*** your path, or set the MINTWRAPPERS_CONFIG environment variable to the"
-       echo "*** full path to mintwrappers-config."
+     if test "$OTOSIS_CONFIG" = "no" ; then
+       echo "*** The otosis-config script installed by otosis could not be found"
+       echo "*** If otosis was installed in PREFIX, make sure PREFIX/bin is in"
+       echo "*** your path, or set the OTOSIS_CONFIG environment variable to the"
+       echo "*** full path to otosis-config."
      else
         :
      fi
-     MINTWRAPPERS_CFLAGS=""
-     MINTWRAPPERS_LIBS=""
+     OTOSIS_CFLAGS=""
+     OTOSIS_LIBS=""
      { echo "configure: error: 
-*** mintwrappers 0.0.0 or better is required. The latest version of mintwrappers
+*** otosis 0.31.0 or better is required. The latest version of otosis
 *** is always available from ftp://ftp.nocrew.org." 1>&2; exit 1; }
   fi
   
   
 
 
-  mintwrappers_cflags=$MINTWRAPPERS_CFLAGS
-  mintwrappers_libs=$MINTWRAPPERS_LIBS
+  otosis_cflags=$OTOSIS_CFLAGS
+  otosis_libs=$OTOSIS_LIBS
 else
-  # Use uninstalled mintwrappers (assume they got the version right)
+  # Use uninstalled otosis (assume they got the version right)
 
-  if test -x $with_mintwrappers/mintwrappers-config ; then 
+  if test -x $with_otosis/otosis-config ; then 
     :
   else
-    { echo "configure: error: mintwrappers directory ($with_mintwrappers) not present or not configured" 1>&2; exit 1; }
+    { echo "configure: error: otosis directory ($with_otosis) not present or not configured" 1>&2; exit 1; }
   fi
 
   # For use in oaesis-config
-  mintwrappers_cflags=`$with_mintwrappers/mintwrappers-config --cflags`
-  mintwrappers_libs=`$with_mintwrappers/mintwrappers-config --libs`
+  otosis_cflags=`$with_otosis/otosis-config --cflags`
+  otosis_libs=`$with_otosis/otosis-config --libs`
 
-  mintwrappers_release=`$with_mintwrappers/mintwrappers-config --version | sed 's%\\.[0-9]*$%%'`
+  otosis_release=`$with_otosis/otosis-config --version | sed 's%\\.[0-9]*$%%'`
 
   # canonicalize relative paths
-  case $with_mintwrappers in 
+  case $with_otosis in 
     /*)
-      mintwrappers_dir=$with_mintwrappers
+      otosis_dir=$with_otosis
       ;;
     *)
-      mintwrappers_dir="\$(top_builddir)/$with_mintwrappers"
+      otosis_dir="\$(top_builddir)/$with_otosis"
       ;;
   esac
 
-  MINTWRAPPERS_CFLAGS="-I$mintwrappers_dir"
-  MINTWRAPPERS_LIBS=$mintwrappers_dir/libfb.la
+  OTOSIS_CFLAGS="-I$otosis_dir"
+  OTOSIS_LIBS=$otosis_dir/libfb.la
 
   
   
 fi
 
-CPPFLAGS="$CPPFLAGS $MINTWRAPPERS_CFLAGS $OVDISIS_CFLAGS"
+CPPFLAGS="$CPPFLAGS $OTOSIS_CFLAGS $OVDISIS_CFLAGS"
 
 OSISINCLUDE=${includedir}/osis
 
@@ -2779,9 +2779,9 @@ s%@LIBTOOL@%$LIBTOOL%g
 s%@OVDISIS_CONFIG@%$OVDISIS_CONFIG%g
 s%@OVDISIS_CFLAGS@%$OVDISIS_CFLAGS%g
 s%@OVDISIS_LIBS@%$OVDISIS_LIBS%g
-s%@MINTWRAPPERS_CONFIG@%$MINTWRAPPERS_CONFIG%g
-s%@MINTWRAPPERS_CFLAGS@%$MINTWRAPPERS_CFLAGS%g
-s%@MINTWRAPPERS_LIBS@%$MINTWRAPPERS_LIBS%g
+s%@OTOSIS_CONFIG@%$OTOSIS_CONFIG%g
+s%@OTOSIS_CFLAGS@%$OTOSIS_CFLAGS%g
+s%@OTOSIS_LIBS@%$OTOSIS_LIBS%g
 s%@CPP@%$CPP%g
 s%@LT_VERSION_INFO@%$LT_VERSION_INFO%g
 s%@OSISINCLUDE@%$OSISINCLUDE%g
